---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-15-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-15-2
  template:
    metadata:
      labels:
        app: app-15-2
    spec:
      containers:
        - name: react-app
          image: hothaifaz11/react-app
          ports:
            - containerPort: 3000
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
