---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: app-15-2
    container: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
