---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: my-app
    container: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
